export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const CURRENT_USER_POSTS_UPDATE = "CURRENT_USER_POSTS_UPDATE";
export const CURRENT_USER_EVENTS_UPDATE = "CURRENT_USER_EVENTS_UPDATE";
export const ALL_USERS_EVENTS_UPDATE = "ALL_USERS_EVENTS_UPDATE";
export const ALL_USERS_OF_THE_EVENT = "ALL_USERS_OF_THE_EVENT";
export const CURRENT_CHAT_MESSAGES_UPDATE = "CURRENT_CHAT_MESSAGES_UPDATE";
export const CURRENT_LOOKING_EVENT_CHANGE = "CURRENT_LOOKING_EVENT_CHANGE";
